name: flutter_news
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  provider: ^3.1.0
  flutter_screenutil: ^0.5.3
  flutter_easyrefresh: ^2.0.4
  sprintf: ^4.0.2
  flutter_swiper: ^1.1.6
  dio: ^2.1.13
  video_player: ^0.6.4
  flutter_webview_plugin: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/news_tab_top_logo.png
    - images/news_tab_top_logo_small.png
    - images/icon_find.png
    - images/icon_news_search.png
    - images/close.png
    - images/tag_video_item_play.png
    - images/tag_video_list_comment.png
    - images/tag_video_list_more_tools.png
    - images/tag_video_support_click.png
    - images/tag_video_support_unclick.png

    - images/2.0x/news/news_1.png
    - images/2.0x/news/news_2.png
    - images/2.0x/news/news_3.png
    - images/2.0x/news/news_4.png
    - images/2.0x/news/news_5.png
    - images/2.0x/news/news_6.png
    - images/2.0x/news/news_7.png
    - images/2.0x/news/news_8.png
    - images/2.0x/news/news_9.png
    - images/2.0x/news/news_10.png
    - images/2.0x/news/news_11.png
    - images/2.0x/news/news_12.png
    - images/2.0x/news/news_13.png
    - images/2.0x/news/news_14.png
    - images/2.0x/news/news_15.png

    - images/2.0x/video/video_1.png
    - images/2.0x/video/video_2.png
    - images/2.0x/video/video_3.png
    - images/2.0x/video/video_4.png
    - images/2.0x/video/video_5.png
    - images/2.0x/video/video_6.png
    - images/2.0x/video/video_7.png
    - images/2.0x/video/video_8.png
    - images/2.0x/video/video_9.png
    - images/2.0x/video/video_10.png
    - images/2.0x/video/video_11.png
    - images/2.0x/video/video_12.png
    - images/2.0x/video/video_13.png
    - images/2.0x/video/video_14.png
    - images/2.0x/video/video_15.png

    - images/2.0x/square/square_1.png
    - images/2.0x/square/square_2.png
    - images/2.0x/square/square_3.png
    - images/2.0x/square/square_4.png
    - images/2.0x/square/square_5.png
    - images/2.0x/square/square_6.png
    - images/2.0x/square/square_7.png
    - images/2.0x/square/square_8.png
    - images/2.0x/square/square_9.png
    - images/2.0x/square/square_10.png
    - images/2.0x/square/square_11.png
    - images/2.0x/square/square_12.png
    - images/2.0x/square/square_13.png
    - images/2.0x/square/square_14.png

    - images/2.0x/account/account_1.png
    - images/2.0x/account/account_2.png
    - images/2.0x/account/account_3.png
    - images/2.0x/account/account_4.png
    - images/2.0x/account/account_5.png
    - images/2.0x/account/account_6.png
    - images/2.0x/account/account_7.png
    - images/2.0x/account/account_8.png
    - images/2.0x/account/account_9.png
    - images/2.0x/account/account_10.png
    - images/2.0x/account/account_11.png
    - images/2.0x/account/account_12.png
    - images/2.0x/account/account_13.png
    - images/2.0x/account/account_14.png
    - images/2.0x/account/account_15.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
